#!/usr/bin/env bash

# Helper for Debian installs,
# meant to be sourced from pmb-init and pmb-add scripts

# clean up previous
if [ -e /tmp/sysconf.txt ]
then
    rm /tmp/sysconf.txt || true
fi

# hostname?
if [[ -v hostname ]]
then
    echo "hostname=${hostname}" >> /tmp/sysconf.txt
fi

# public key for root?
if [[ -v root_authorized_key ]]
then
    echo "root_authorized_key=$root_authorized_key" >> /tmp/sysconf.txt
fi

# Mount boot and root partitions
boot_mnt=/tmp/$(date +%S%N)
mkdir "$boot_mnt"
mount "$part1" "$boot_mnt"
root_mnt=/tmp/$(date +%S%N)
mkdir "$root_mnt"
mount "$part2" "$root_mnt"

# If `/tmp/sysconf.txt` was created, add it as appropriate
if [ -e /tmp/sysconf.txt ]
then
    case $(basename "$0") in 
        "pmb-add")
            echo "add to TAR"
            ;;
        "pmb-init")
            echo "add to /boot/firmware"
            mv /tmp/sysconf.txt "$boot_mnt"
            ;;
        *)
            echo "who is $0 which called 'helper-debian'"
            exit 1
            ;;
    esac
fi

# tweak the root specification in `cmdline.txt` and 
# "$root_mnt"/etc/default/raspi-firmware

sed -i "s/LABEL=RASPIROOT/PARTUUID=${partuuid}/" "$boot_mnt"/cmdline.txt
# comment `ROOTPART=LABEL=RASPIROOT` in "$root_mnt"/etc/default/raspi-firmware
sed -i "s/^ROOTPART=LABEL=RASPIROOT/ROOTPART=PARTUUID=${partuuid}/" "$root_mnt"/etc/default/raspi-firmware

umount "$boot_mnt" "$root_mnt"
rm -r "$boot_mnt" "$root_mnt"
