#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset
############### end of Boilerplate

## Code to swap between from one OS installation on storage media to another.
# Requires env var
# * label - Used to identify the next OS partition and related information 
#   stored in the pmb-system labeled partition.

usage() {
    echo "$0 <os_label> <device>"
    echo "Label of EXT4 filesystem where target OS has been installed."
    echo "device which contains the 'pmb-system' filesystem"
    exit 1
}

# pull in helpers
source "$(dirname "$0")/pmb-helpers"

# Check for first arg - label
if [[ -v 1 ]]
then
    root_label=$(findmnt -n -o SOURCE /)
    label="$1"
    if [ "$root_label" == "$label" ]
    then
        echo "$root_label is already in use"
        usage
    fi

    # find info partition
    if [[ -v 2 ]]
    then
        device="$2"
        if [ -e "${device}5" ]
        then
            part5=${device}5
            # partbase=${device}
        elif [ -e "${device}p5" ]
        then
            part5="${device}p5"
            # partbase=${device}p
        else
            echo "Can't find partition 5 on $device"
            usage
        fi
    else
        usage
    fi
else
    usage
fi

# Mount info partition
pmb_system_mnt=/tmp/$(date +%S%N)
mkdir "$pmb_system_mnt"
mount "${part5}" "$pmb_system_mnt"

# fixup (or bail if $label does not represent an available OS)
fixup_OS_info

## Mount the "next" OS partition
target_mnt=/tmp/$(date +%S%N)
mkdir "$target_mnt"
mount PARTUUID="$PARTUUID" "$target_mnt"

## Check for boot image
if [ ! -e "$target_mnt"/root/boot_part/backup.tar ]
then
    echo "boot backup .../root/boot_part/backup.tar for $label not found"
    umount "$target_mnt"
    rm -r "$target_mnt"
    exit 1
fi

## Backup current boot partition
mkdir -p /root/boot_part/
if ! tar cf /root/boot_part/backup.tar /boot/firmware
then
    echo "cannot backup /boot/firmware to /root/boot_part/backup.tar"
    umount "$target_mnt"
    rm -r "$target_mnt"
    exit 1
fi

## No turning back after this (except to restore the previous boot part)

## Clear the boot part and install target boot partition components
rm -rf /boot/firmware/*
tar --strip-components=2 --directory=/boot/firmware \
    -xf "$target_mnt"/root/boot_part/backup.tar

## Execute the helper when provided to complete prep for the next OS.
if [[ -v helper ]]
then
    if [ -e "$helper" ]
    then
        # shellcheck disable=SC1090 # ShellCheck can't follow non-const...
        source "$helper"
        echo "helper=$helper" >> "$pmb_system_mnt/OS_list/$label"
    else
        echo "helper script \"$helper\" not found"
    fi
fi

## TODO umount info and target partitions