#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset
############### end of Boilerplate

# script to add a Pi installation for multiboot using "pmb"
# Requires env vars
# * size - indicate the size of the resulting EXT4 partition
#          see the man page for sfdisk for units (e.g. size=10G)
# * device which holds a fresh unbooted RpiOS (or other) install
#   (e.g. device=/dev/sdb or device=/dev/mmcblk0)
